Script started on 2021-09-15 14:47:46+00:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="238" LINES="60"]
1631715942.149995
1631716054.675339
Waiting for query to complete ...
Waiting for query to complete ...
Waiting for query to complete ...
Downloaded: 246
Unknonw: 6204b156-692a-4548-b41d-7d18f779dd00
Unknonw: 2a15928a-3a5b-4c86-876d-34d2d4c307a4
Unknonw: 142f4028-8945-4951-a40f-838f06fbe367
Finished, found: 120 results
Waiting for query to complete ...
Waiting for query to complete ...
Waiting for query to complete ...
Downloaded: 246
Unknonw: 674d0437-cc39-48c5-84ef-dd1d36948333
Unknonw: f403cb15-78ca-4de4-9014-aad409d9d745
Unknonw: d144c297-5e3e-4aaa-bb4b-8436e1da400c
Unknonw: 38fdda4d-1ba0-44fc-8599-5c1d8f07228b
Unknonw: 553e4f03-9516-4b3d-8c87-5a67fbe5874e
Unknonw: b2afb613-b02b-4369-b493-ca053affaa3a
Unknonw: 3ba9cb8b-c317-4844-a6eb-bbc4bccaa690
Finished, found: 116 results
Traceback (most recent call last):
  File "log_query.py", line 116, in <module>
    df.to_csv(f"{args.output}_{memory}_processed.csv")
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/pandas/core/generic.py", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 237, in save
    with get_handle(
  File "/home/ubuntu/data/python-venv/lib/python3.8/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '....data/write/dynamo_4_128_processed.csv'

Script done on 2021-09-15 14:47:53+00:00 [COMMAND_EXIT_CODE="1"]
